### ISSUE TITLE
Set up linting rules and pipeline

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#42] opened 2022-07-26 03:36 UTC
# requirements 

- Linting rules are updated based on team's spec. 
- linter is ran on PRs. 
- All files in project have been linted and updated

**Comment by ann-kilzer** [comment] 2022-10-09 12:46
Is this a duplicate of #20

**Comment by ermish** [comment] 2022-10-09 12:55
@ann-kilzer separate. One is for running our test suite and the other is for running our linters

**Comment by ann-kilzer** [comment] 2022-10-09 13:19
I misread 😆

**Closed** 2022-10-18 15:47 UTC
Labels: hacktober-prep
